apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-reverse-proxy
  name: udagram-reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udagram-reverse-proxy
  template:
    metadata:
      labels:
        service: udagram-reverse-proxy
    spec:
      containers:
      - image: abakam/udagram-reverse-proxy
        name: udagram-reverse-proxy
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-reverse-proxy
  name: udagram-reverse-proxy
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: udagram-reverse-proxy
  type: LoadBalancer