apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-user-service
  name: udagram-user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udagram-user-service
  template:
    metadata:
      labels:
        service: udagram-user-service
    spec:
      containers:
      - image: abakam/udagram-user-service
        name: udagram-user-service
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        env:
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: udagram-env-config
              key: URL
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: udagram-env-config
              key: JWT_SECRET
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: udagram-env-config
              key: POSTGRES_DB
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: udagram-env-config
              key: POSTGRES_HOST
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: udagram-env-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: udagram-env-secret
              key: POSTGRES_USERNAME
      restartPolicy: Always

---


apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-user-service
  name: udagram-user-service
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: udagram-user-service